# pick which poll to view [feature]
# which sub-polls are 'live' on RCP [feature]
# current date [feature]
# closing date [feature]
# segments for sale [feature]
# market prices [feature]
# output: 'fair' price of each future [feature]
# input portfolio size/cash [feature]
# view portfolio value over time [feature]
# kelly criterion bet size recommendation [feature]