library(xts)
library(lubridate)
library(TTR)
library(PerformanceAnalytics)
library(PortfolioAnalytics)
library(DEoptim)
library(doParallel)
library(httr)
library(plyr)
library(digest)
library(RCurl)
library(stringr)
library(slackr)
library(httr)
library(quantstrat) # install.packages("quantstrat", repos="http://R-Forge.R-project.org")
library(IKTrading)  # install_github("IlyaKipnis/IKTrading") needs devtools
library(lattice)
library(doParallel)